image: maven/maven:3-jdk-11

options:
  size: 2x

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B -e -Djava.awt.headless=true clean install
  custom:
    deploy:
      - step:
          caches:
            - maven
          script:
            - mvn -B -e -Djava.awt.headless=true -s settings.xml clean deploy -DaltDeploymentRepository=deploymentRepo::default::$DEPLOYMENT_SNAPSHOT_REPO
